# Generated by Django 3.1.1 on 2020-09-29 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('savetime', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
