# Generated by Django 3.1.1 on 2020-09-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.CharField(choices=[('active', 'active'), ('notactive', 'notactive')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
